In [2]:
def int_exception():
    while True:
        try:
            num=int(input("Enter the Integer:"))
            avg=5/num
        except ZeroDivisionError as e:
            
            print(e)
            continue
        else:
            print("Great! The Number is greater than Zero ",avg)
            break
    return "Now, Able to access"
print(int_exception())
            

Enter the Integer:0
division by zero
Enter the Integer:8
Great! The Number is greater than Zero  0.625
Now, Able to access


In [112]:
def play():
    subjects=(["Americans ","Indians"])
    verbs=(["play","watch"])
    objects=(["Baseball","Cricket"])

    n= [subjects[i]+" "+j+" "+k for k in objects for j in verbs for i in range(len(subjects))]
    for i in n:
        yield i
print(play())

<generator object play at 0x000002291E63CE48>


In [113]:
g=play()
g

<generator object play at 0x000002291E63CDC8>

In [114]:
next(g)

'Americans  play Baseball'

In [115]:
next(g)

'Indians play Baseball'

In [116]:
next(g)

'Americans  watch Baseball'

In [117]:
for i in play():
    print(i)

Americans  play Baseball
Indians play Baseball
Americans  watch Baseball
Indians watch Baseball
Americans  play Cricket
Indians play Cricket
Americans  watch Cricket
Indians watch Cricket


In [127]:
lst=[1,2,3,4,5]
m=int(input("Enter the no:of column of output matrix: "))
power=list(map(lambda n:n*2 ,lst))
print(power)

Enter the no:of column of output matrix: 2
[2, 4, 6, 8, 10]


In [7]:
import numpy as np

def matrix(m,n):
    lst=[1,2,3,4,5]
    num=len(lst)
    dec,inc=[],[]
    
    if m==1:        
        l1=np.array([[[row **i for i in range(n)] for row in range(1,num+1)]])
        for i in l1:
            yield i     
    else:
        l2=np.array([[[row **(n-1-i) for i in range(n)]  for row in range(1,num+1)]])
        for i in l2:
            yield i 
            
n=int(input("Enter the no: of Column to be printed: "))             
result=int(input("Enter the choice of decreasing/Increasing :"))
print(matrix(result,n))

Enter the no: of Column to be printed: 5
Enter the choice of decreasing/Increasing :1
<generator object matrix at 0x00000182994613C8>


In [8]:
for i in matrix(result,n):
    print(i)

[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
